name: mini-pipeline

on:
  workflow_dispatch:           # enables the Run workflow button
  push:
    paths:
      - "PipelineDemo/**"
      - ".github/workflows/mini-pipeline.yml"

permissions:
  contents: write              # needed to commit outputs

jobs:
  mini:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: (debug) show repo
        run: |
          pwd
          ls -la
          ls -la PipelineDemo || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: PipelineDemo
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        working-directory: PipelineDemo
        run: python src/pipeline.py

      - name: Commit generated outputs
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            PipelineDemo/data/processed
            PipelineDemo/reports
            PipelineDemo/site
          message: "ci(mini): update demo outputs"
