name: mini-pipeline

on:
  workflow_dispatch:       # <-- restores the "Run workflow" button
  push:                    # optional: also run on changes to the demo
    branches: [ main ]
    paths:
      - 'PipelineDemo/**'
      - '.github/workflows/mini-pipeline.yml'

permissions:
  contents: write          # needed to commit generated outputs

jobs:
  mini:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show repo (debug)
        run: |
          pwd
          ls -al
          ls -al PipelineDemo || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

          - name: Debug paths (temporary)
      run: |
        echo "PWD:"; pwd
        echo "Root listing:"; ls -la
        echo "PipelineDemo listing:"; ls -la "$GITHUB_WORKSPACE/PipelineDemo"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r "$GITHUB_WORKSPACE/PipelineDemo/requirements.txt"

    - name: Run pipeline
      working-directory: PipelineDemo
      run: python src/pipeline.py

      - name: Run pipeline
        run: python PipelineDemo/src/pipeline.py

      - name: Commit generated outputs
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            PipelineDemo/data/processed
            PipelineDemo/reports
            PipelineDemo/site
          message: "ci(pipeline): update demo outputs"
