name: mini-pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - 'PipelineDemo/src/**'
      - 'PipelineDemo/requirements.txt'
      - '.github/workflows/mini-pipeline.yml'

permissions:
  contents: write

concurrency:
  group: mini-pipeline-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mini:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: (debug) verify files
        run: |
          pwd && ls -la
          test -f requirements.txt  || echo "::notice::no requirements.txt — skipping pip install"
          test -f src/pipeline.py   || echo "::notice::no src/pipeline.py — will skip run"

      - name: Install dependencies (if present)
        if: ${{ hashFiles('PipelineDemo/requirements.txt') != '' }}
        run: pip install -r requirements.txt

      - name: Run pipeline (if present)
        if: ${{ hashFiles('PipelineDemo/src/pipeline.py') != '' }}
        run: python src/pipeline.py

      # commit outputs (relative to PipelineDemo) 
      - name: Commit generated outputs
        if: ${{ github.event_name == 'push' }}
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            data/processed
            reports
            site
          message: "ci(mini): run pipeline and update outputs"
          default_author: github_actions
          skip_empty: true
