name: mini-pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - 'PipelineDemo/src/**'
      - 'PipelineDemo/requirements.txt'
      - '.github/workflows/mini-pipeline.yml'

permissions:
  contents: write

concurrency:
  group: mini-pipeline-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mini:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: (debug) show repo
        run: |
          pwd
          ls -la
          ls -la PipelineDemo || true

      - name: Install dependencies (if present)
        run: |
          if [ -f PipelineDemo/requirements.txt ]; then
            pip install -r PipelineDemo/requirements.txt
          else
            echo "::notice file=PipelineDemo/requirements.txt::no requirements.txt — skipping pip install"
          fi

      - name: Run pipeline (if present)
        run: |
          if [ -f PipelineDemo/src/pipeline.py ]; then
            python PipelineDemo/src/pipeline.py
          else
            echo "::notice file=PipelineDemo/src/pipeline.py::no pipeline.py — skipping run"
          fi

      - name: Commit generated outputs
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            PipelineDemo/data/processed
            PipelineDemo/reports
            PipelineDemo/site
          message: "ci(mini): update mini-pipeline outputs"
          default_author: github_actions
          skip_empty: true
