name: mini-pipeline

on:
  workflow_dispatch:
  push:
    # only retrigger when source or the workflow changes (avoid loops on output commits)
    paths:
      - 'PipelineDemo/src/**'
      - 'PipelineDemo/requirements.txt'
      - '.github/workflows/mini-pipeline.yml'

permissions:
  contents: write

concurrency:
  group: mini-pipeline-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mini:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: PipelineDemo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: (debug) show repo
        run: |
          pwd
          ls -la
          ls -la src || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: (debug) verify paths
        run: |
          pwd
          ls -la
          ls -la src || true
          # Make these non-fatal while debugging; remove "|| true" to enforce.
          test -f requirements.txt || { echo "Missing requirements.txt"; ls -la; exit 1; }
          test -f src/pipeline.py || { echo "Missing src/pipeline.py"; ls -la src; exit 1; }

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        run: python src/pipeline.py

      - name: Commit generated outputs
        uses: EndBug/add-and-commit@v9
        with:
          skip_empty: true
          add: |
            PipelineDemo/data/processed
            PipelineDemo/reports
            PipelineDemo/site
          message: "ci(mini): commit mini-pipeline outputs"
          default_author: github_actions

