name: mini-pipeline

on:
  # manual run button + re-run on changes in the demo folder
  workflow_dispatch:
  push:
    paths:
      - "PipelineDemo/**"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show repo tree (debug)
        run: ls -R

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: PipelineDemo
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        working-directory: PipelineDemo
        run: python src/pipeline.py

      - name: Commit generated outputs
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            PipelineDemo/data/processed
            PipelineDemo/reports
            PipelineDemo/site
          message: "ci(pipeline): publish demo outputs [skip ci]"
          default_author: github_actions
