name: mini-pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - "PipelineDemo/**"

permissions:
  contents: write

jobs:
  mini:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show repo root (debug)
        run: |
          pwd
          ls -la

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

          - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r PipelineDemo/requirements.txt

      - name: Run pipeline
        working-directory: PipelineDemo
        run: python src/pipeline.py

      - name: Commit generated outputs
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            PipelineDemo/data/processed
            PipelineDemo/reports
            PipelineDemo/site
          message: "ci(pipeline): publish mini pipeline outputs"
          default_author: github_actions
