name: mini-pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - 'PipelineDemo/**'

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r PipelineDemo/requirements.txt

      - name: Run pipeline
        run: python PipelineDemo/src/pipeline.py

      - name: Commit generated outputs
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            PipelineDemo/data/processed
            PipelineDemo/reports/summary.md
            PipelineDemo/site
          message: "ci: update mini pipeline outputs"
          default_author: github_actions
