name: mini-pipeline

on:
  workflow_dispatch:
  push:
    # only retrigger when source or the workflow changes (avoid loops on output commits)
    paths:
      - 'PipelineDemo/src/**'
      - 'PipelineDemo/requirements.txt'
      - '.github/workflows/mini-pipeline.yml'

permissions:
  contents: write

jobs:
  mini:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: PipelineDemo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: (debug) show repo
        run: |
          pwd
          ls -la
          ls -la src || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        run: |
          # if your script is at PipelineDemo/src/pipeline.py keep this line;
          # if it lives at PipelineDemo/pipeline.py change to "python pipeline.py"
          python src/pipeline.py

      - name: Commit generated outputs
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            PipelineDemo/data/processed
            PipelineDemo/reports
            PipelineDemo/site
          message: "ci(mini): update demo outputs"
