name: mini-pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - 'PipelineDemo/src/**'
      - 'PipelineDemo/requirements.txt'
      - '.github/workflows/mini-pipeline.yml'

permissions:
  contents: write

concurrency:
  group: mini-pipeline-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mini:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: PipelineDemo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        run: python src/pipeline.py

      - name: Commit generated outputs
        if: ${{ github.event_name == 'push' }}
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            data/processed
            reports
            site
          message: "ci(mini): run pipeline and update outputs"
          default_author: github_actions

      - name: Upload site artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mini-pipeline-site
          # actions/* paths are repo-root relative
          path: PipelineDemo/site
